import type { Property } from './types'

const kitchen = { url: '/properties/interior-kitchen.png', alt: 'Kitchen' }
const bedroom = { url: '/properties/interior-bedroom.png', alt: 'Bedroom' }
const bathroom = { url: '/properties/interior-bathroom.png', alt: 'Bathroom' }

// Local fallback content used until a real Sanity project is connected.
export const demoProperties: Property[] = [
  {
    _id: 'demo-1',
    slug: 'amsterdam-canal-apartment',
    title: {
      en: 'Bright Canal-View Apartment',
      nl: 'Licht appartement met grachtzicht',
      ar: 'شقة مضيئة بإطلالة على القناة',
    },
    description: {
      en: 'A stunning apartment overlooking one of Amsterdam most beautiful canals. Featuring floor-to-ceiling windows, a fully equipped kitchen and a spacious living area bathed in natural light. Perfect for professionals or couples looking for a central home.',
      nl: 'Een prachtig appartement met uitzicht op een van de mooiste grachten van Amsterdam. Met vloer-tot-plafond ramen, een volledig uitgeruste keuken en een ruime woonkamer vol natuurlijk licht. Perfect voor professionals of stellen die een centrale woning zoeken.',
      ar: 'شقة رائعة تطل على واحدة من أجمل قنوات أمستردام. تتميز بنوافذ ممتدة من الأرض إلى السقف ومطبخ مجهز بالكامل ومنطقة معيشة واسعة غارقة في الضوء الطبيعي. مثالية للمهنيين أو الأزواج الباحثين عن منزل مركزي.',
    },
    type: 'apartment',
    price: 1850,
    currency: 'EUR',
    city: 'Amsterdam',
    address: 'Prinsengracht 263, 1016 GV Amsterdam',
    bedrooms: 2,
    bathrooms: 1,
    area: 78,
    amenities: ['WiFi', 'Heating', 'Washing machine', 'Dishwasher', 'Balcony', 'Furnished'],
    images: [
      { url: '/properties/amsterdam-canal-apartment.png', alt: 'Living room with canal view' },
      kitchen,
      bedroom,
      bathroom,
    ],
    featured: true,
    availableFrom: '2026-08-01',
  },
  {
    _id: 'demo-2',
    slug: 'rotterdam-modern-townhouse',
    title: {
      en: 'Modern Townhouse near the Center',
      nl: 'Moderne herenhuis nabij het centrum',
      ar: 'منزل حديث بالقرب من المركز',
    },
    description: {
      en: 'A spacious three-bedroom townhouse in a quiet Rotterdam neighborhood. Recently renovated with a modern kitchen, private garden and a garage. Close to schools, shops and public transport.',
      nl: 'Een ruim herenhuis met drie slaapkamers in een rustige wijk in Rotterdam. Recent gerenoveerd met een moderne keuken, privétuin en garage. Dicht bij scholen, winkels en openbaar vervoer.',
      ar: 'منزل واسع من ثلاث غرف نوم في حي هادئ في روتردام. تم تجديده حديثاً بمطبخ عصري وحديقة خاصة وجراج. قريب من المدارس والمتاجر والمواصلات العامة.',
    },
    type: 'house',
    price: 2400,
    currency: 'EUR',
    city: 'Rotterdam',
    address: 'Blaak 12, 3011 TA Rotterdam',
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    amenities: ['WiFi', 'Heating', 'Garden', 'Garage', 'Dishwasher', 'Pets allowed'],
    images: [
      { url: '/properties/rotterdam-townhouse.png', alt: 'Townhouse exterior' },
      bedroom,
      kitchen,
      bathroom,
    ],
    featured: true,
    availableFrom: '2026-09-01',
  },
  {
    _id: 'demo-3',
    slug: 'utrecht-cozy-studio',
    title: {
      en: 'Cozy Studio in the Heart of Utrecht',
      nl: 'Gezellige studio in het hart van Utrecht',
      ar: 'استوديو مريح في قلب أوتريخت',
    },
    description: {
      en: 'A charming furnished studio ideal for students or singles. Everything you need in one bright, efficient space, just a few minutes walk from Utrecht Central Station and the old town.',
      nl: 'Een charmante gemeubileerde studio, ideaal voor studenten of alleenstaanden. Alles wat je nodig hebt in één lichte, efficiënte ruimte, op enkele minuten lopen van Utrecht Centraal en de oude binnenstad.',
      ar: 'استوديو مفروش وساحر مثالي للطلاب أو العزّاب. كل ما تحتاجه في مساحة واحدة مضيئة وعملية، على بعد دقائق قليلة سيراً على الأقدام من محطة أوتريخت المركزية والبلدة القديمة.',
    },
    type: 'studio',
    price: 950,
    currency: 'EUR',
    city: 'Utrecht',
    address: 'Oudegracht 100, 3511 AV Utrecht',
    bedrooms: 1,
    bathrooms: 1,
    area: 34,
    amenities: ['WiFi', 'Heating', 'Furnished', 'Washing machine'],
    images: [
      { url: '/properties/utrecht-studio.png', alt: 'Studio interior' },
      kitchen,
      bathroom,
    ],
    featured: false,
    availableFrom: '2026-07-15',
  },
  {
    _id: 'demo-4',
    slug: 'the-hague-luxury-villa',
    title: {
      en: 'Luxury Villa with Private Pool',
      nl: 'Luxe villa met privézwembad',
      ar: 'فيلا فاخرة مع مسبح خاص',
    },
    description: {
      en: 'An exclusive villa offering the ultimate in comfort and privacy. Enjoy a heated swimming pool, landscaped garden, home cinema and five generous bedrooms. Located in a prestigious residential area of The Hague.',
      nl: 'Een exclusieve villa die het ultieme comfort en privacy biedt. Geniet van een verwarmd zwembad, aangelegde tuin, thuisbioscoop en vijf royale slaapkamers. Gelegen in een prestigieuze woonwijk van Den Haag.',
      ar: 'فيلا حصرية توفر أقصى درجات الراحة والخصوصية. استمتع بمسبح مُدفأ وحديقة منسقة وسينما منزلية وخمس غرف نوم واسعة. تقع في منطقة سكنية مرموقة في لاهاي.',
    },
    type: 'villa',
    price: 5200,
    currency: 'EUR',
    city: 'The Hague',
    address: 'Van Stolkweg 25, 2585 JN The Hague',
    bedrooms: 5,
    bathrooms: 3,
    area: 320,
    amenities: ['WiFi', 'Swimming pool', 'Garden', 'Garage', 'Air conditioning', 'Home cinema', 'Furnished'],
    images: [
      { url: '/properties/the-hague-villa.png', alt: 'Villa with pool' },
      bedroom,
      kitchen,
      bathroom,
    ],
    featured: true,
    availableFrom: '2026-10-01',
  },
  {
    _id: 'demo-5',
    slug: 'eindhoven-industrial-loft',
    title: {
      en: 'Industrial Loft with High Ceilings',
      nl: 'Industriële loft met hoge plafonds',
      ar: 'لوفت صناعي بأسقف عالية',
    },
    description: {
      en: 'A striking loft in a converted factory building. Exposed brick, oversized windows and an open-plan layout make this a truly unique home for creatives and design lovers.',
      nl: 'Een opvallende loft in een verbouwd fabrieksgebouw. Zichtbaar metselwerk, grote ramen en een open indeling maken dit een unieke woning voor creatievelingen en designliefhebbers.',
      ar: 'لوفت مذهل في مبنى مصنع تم تحويله. الطوب المكشوف والنوافذ الضخمة والتصميم المفتوح تجعله منزلاً فريداً حقاً لمحبي الإبداع والتصميم.',
    },
    type: 'apartment',
    price: 1600,
    currency: 'EUR',
    city: 'Eindhoven',
    address: 'Strijp-S 40, 5617 AA Eindhoven',
    bedrooms: 2,
    bathrooms: 1,
    area: 95,
    amenities: ['WiFi', 'Heating', 'Elevator', 'Furnished', 'Dishwasher'],
    images: [
      { url: '/properties/eindhoven-loft.png', alt: 'Industrial loft interior' },
      kitchen,
      bedroom,
      bathroom,
    ],
    featured: false,
    availableFrom: '2026-08-15',
  },
  {
    _id: 'demo-6',
    slug: 'haarlem-family-house',
    title: {
      en: 'Comfortable Family House with Garden',
      nl: 'Comfortabel gezinshuis met tuin',
      ar: 'منزل عائلي مريح مع حديقة',
    },
    description: {
      en: 'A warm and welcoming family home in a green Haarlem suburb. Bright living room, modern kitchen and a sunny south-facing garden. Ideal for families looking for space and tranquility.',
      nl: 'Een warm en gastvrij gezinshuis in een groene wijk van Haarlem. Lichte woonkamer, moderne keuken en een zonnige tuin op het zuiden. Ideaal voor gezinnen die ruimte en rust zoeken.',
      ar: 'منزل عائلي دافئ ومرحب في ضاحية خضراء في هارلم. غرفة معيشة مضيئة ومطبخ عصري وحديقة مشمسة تواجه الجنوب. مثالي للعائلات الباحثة عن المساحة والهدوء.',
    },
    type: 'house',
    price: 2100,
    currency: 'EUR',
    city: 'Haarlem',
    address: 'Florapark 8, 2012 HK Haarlem',
    bedrooms: 4,
    bathrooms: 2,
    area: 165,
    amenities: ['WiFi', 'Heating', 'Garden', 'Washing machine', 'Dishwasher', 'Pets allowed'],
    images: [
      { url: '/properties/haarlem-house.png', alt: 'Family house living room' },
      kitchen,
      bedroom,
      bathroom,
    ],
    featured: false,
    availableFrom: '2026-09-15',
  },
]
